### ISSUE TITLE
Bling-Phong shader looks 'per-vertex' 

### ISSUE THREAD

**Issue by daybson** [PacktPublishing/Unity-2021-Shaders-and-Effects-Cookbook-Fourth-Edition#1]
I think some normalization is missing on chapter 5 : "Creating a Blinn-Phong Specular type"
The result:
![image](https://user-images.githubusercontent.com/3179898/169157661-6cd641ed-2454-4140-9a4a-69d0ee579a4d.png)

I've add the following normalization at the end of void surf:

```
void surf(Input IN, inout SurfaceOutput o)
{
  half4 c = tex2D(_MainTex, IN.uv_MainTex) * _MainTint;
  o.Albedo = c.rgb;
  o.Alpha = c.a;
  o.Normal = normalize(o.Normal);  // HERE
}
```

The result looks now interpolated per pixel instead per vertex.
![image](https://user-images.githubusercontent.com/3179898/169157986-d31ae1a4-8154-4472-8c95-85eb40f256c3.png)

**Comment by jodoran** [comment]
Thanks for the message, I've pushed the change to the repository.
